/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  AMRating as AmRating
} from './components/am-rating/am-rating';

declare global {
  interface HTMLAmRatingElement extends AmRating, HTMLElement {
  }
  var HTMLAmRatingElement: {
    prototype: HTMLAmRatingElement;
    new (): HTMLAmRatingElement;
  };
  interface HTMLElementTagNameMap {
    "am-rating": HTMLAmRatingElement;
  }
  interface ElementTagNameMap {
    "am-rating": HTMLAmRatingElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "am-rating": JSXElements.AmRatingAttributes;
    }
  }
  namespace JSXElements {
    export interface AmRatingAttributes extends HTMLAttributes {
      allowHalfRatings?: boolean;
      colorOff?: string;
      colorOn?: string;
      colorOutline?: string;
      direction?: string;
      interactive?: boolean;
      maxRating?: number;
      minRating?: number;
      rating?: number;
      reference?: string;
      sbgViewBox?: string;
      svgPoints?: string;
    }
  }
}

